# Aula 1 — Numpy & Pandas (28/10) · Caderno para acompanhar a aula

Turma 9 · Análise de Dados com Python

Execute as células **na ordem**. As células **🎯 Sua vez** são para você resolver.

## 🛒 Nosso caso: Mercadinho Bom Preço

Você é o(a) novo(a) analista. Temos 3 tabelas: **produtos**, **vendas** (ago–set/2026) e **clientes**.

Perguntas do dono: qual produto vende mais? quem vende mais? quanto vendemos por cidade?

## ✅ Checklist do ambiente
Rode a célula abaixo. Se aparecer *Tudo certo!*, estamos prontos.

In [1]:
import numpy as np
import pandas as pd

print('Tudo certo! ✅')

Tudo certo! ✅

# 🧮 Bloco 1 — Numpy: contas em massa

## O que é o Numpy?
NumPy (Numerical Python) é a biblioteca do Python para fazer contas com MUITOS números de uma vez, e muito rápido.

- 🔢 **Contas em massa**: Somar, multiplicar ou tirar a média de milhares de números com uma única linha.
- ⚡ **Muito rápido**: Por baixo, usa código em C, bem mais veloz que um laço for em Python.
- 🧱 **Base de tudo**: O Pandas, o Matplotlib e o scikit-learn são construídos em cima do Numpy.

💡  Para o analista: o Numpy é o "motor" por baixo do Pandas. Entender o Numpy ajuda a entender o Pandas.

## Por que o Numpy é mais rápido que uma lista?
Uma analogia para guardar: carros espalhados × um trem.

**Lista do Python:** cada número fica num lugar diferente da memória, como carros espalhados num estacionamento

**Array do Numpy:** todos os números ficam lado a lado e são do mesmo tipo, como os vagões de um trem

💡  O computador anda muito mais rápido num trem do que buscando carro por carro. E o Numpy ainda usa código em C por baixo.

## Instalando e importando o Numpy
No Colab o Numpy já vem instalado. No seu computador, instale uma vez e importe sempre que precisar:

💡  np é um apelido: todo mundo usa. Sua versão do Numpy pode ser diferente da mostrada aqui, e tudo bem.

In [2]:
# no terminal (só no seu computador):  pip install numpy

print(np.__version__)
print(type(np))

2.5.3
<class 'module'>

## Reajuste de 10%: `for` x Numpy

In [3]:
precos = [28.9, 8.5, 5.2, 18.9]
novos = []
for p in precos:
    novos.append(round(p * 1.10, 2))
print(novos)

[31.79, 9.35, 5.72, 20.79]

In [4]:
precos = np.array([28.9, 8.5, 5.2, 18.9])
novos = np.round(precos * 1.10, 2)
print(novos)

[31.79  9.35  5.72 20.79]

## Na prática: quanto mais rápido?
Vamos medir: dobrar 1 milhão de números com uma lista e com um array.

💡  Os tempos variam de computador para computador, mas o array é sempre muito mais rápido. Com poucos números tanto faz; com milhões, faz toda a diferença.

In [11]:
from time import perf_counter

n = 1_000_000
lista = list(range(n))
array = np.arange(n)

t0 = perf_counter()
dobro_lista = [x * 2 for x in lista]
t1 = perf_counter()
dobro_array = array * 2
t2 = perf_counter()

print('lista:', round(t1 - t0, 4), 's')
print('numpy:', round(t2 - t1, 4), 's')
print('numpy é', round((t1 - t0) / (t2 - t1)), 'vezes mais rápido')

lista: 0.0293 s
numpy: 0.0011 s
numpy é 26 vezes mais rápido

## O que é um array?
Um array é uma "lista turbinada": guarda vários valores numa única variável, todos do MESMO tipo, e faz contas com todos de uma vez.

💡  lista * 2 REPETE a lista · array * 2 MULTIPLICA cada elemento. É a diferença mais importante para quem está começando.

In [12]:
lista = [1, 2, 3]
array = np.array([1, 2, 3])

print(lista * 2)
print(array * 2)
print(type(lista))
print(type(array))
print(array.dtype)

[1, 2, 3, 1, 2, 3]
[2 4 6]
<class 'list'>
<class 'numpy.ndarray'>
int64

## Criando um array
Um array 1D vem de uma lista; um array 2D (tabela) vem de uma lista de listas:

💡  Os colchetes de fora formam o array. Cada colchete de dentro é uma LINHA da tabela.

In [13]:
precos = np.array([28.9, 8.5, 5.2, 18.9])
print(precos)

estoque = np.array([40, 120, 80, 35])
print(estoque)

tabela = np.array([[28.9, 40],
                   [8.5, 120],
                   [5.2, 80]])
print(tabela)

[28.9  8.5  5.2 18.9]
[ 40 120  80  35]
[[ 28.9  40. ]
 [  8.5 120. ]
 [  5.2  80. ]]

## Atalhos para criar arrays
Não precisa digitar tudo: o Numpy cria arrays prontos.

💡  arange(início, fim, passo) é o range() que devolve array · o fim NÃO entra · linspace(início, fim, n) divide em n pontos iguais.

In [14]:
print(np.zeros(5))
print(np.ones((2, 3)))
print(np.full(4, 9.9))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[9.9 9.9 9.9 9.9]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]

## Onde o Numpy é usado
Para que serve na prática? Sempre que há MUITOS números para somar, filtrar ou comparar:

- 🛒 **Estoque e vendas**: Totais, médias e filtros sobre milhares de itens vendidos.
- 🏥 **Saúde e sensores**: Milhares de leituras de batimentos ou temperatura por minuto.
- 💹 **Finanças**: Histórico de preços de ações: 252 dias × 50 ações.
- 🌡️ **Clima**: Temperaturas de 365 dias, analisadas por estação do ano.
- 🧑‍🎓 **Escola**: Notas de turmas: alunos × matérias × bimestres.
- 🖼️ **Imagens**: Uma foto é uma tabela de números (os pixels).

💡  Em todos os casos o padrão é o mesmo: muitos números, a mesma conta para todos.

## Conhecendo um array: shape, ndim, size, dtype
Todo array tem "características" que você consulta, sem parênteses:

💡  shape = (linhas, colunas) · ndim = nº de dimensões · size = total de elementos · dtype = tipo dos elementos · len = nº de linhas

In [15]:
vendas = np.array([[120, 150, 130, 160],
                   [90, 110, 100, 130],
                   [70, 80, 95, 85]])

print(vendas.shape)
print(vendas.ndim)
print(vendas.size)
print(vendas.dtype)
print(len(vendas))

(3, 4)
2
12
int64
3

## Dimensões: 1D, 2D e 3D
O shape diz quantas dimensões existem e o tamanho de cada uma:

- 1D **Vetor · (5,)**: Uma linha de valores. Ex.: temperatura de 5 dias, ou os preços dos produtos.
- 2D **Matriz · (3, 4)**: Linhas × colunas, como uma planilha. Ex.: 3 lojas × 4 semanas de vendas.
- 3D **Tensor · (2, 3, 4)**: Camadas de tabelas. Ex.: alunos × matérias × bimestres, ou uma imagem colorida.

💡  Pense nas dimensões como: 1D = uma linha · 2D = uma tabela · 3D = uma pilha de tabelas.

## Um array tem um tipo só
Todos os elementos de um array são do MESMO tipo. Se misturar, o Numpy escolhe um tipo que sirva para todos:

💡  int64 = inteiros · float64 = decimais · <U = texto · astype() converte o tipo (e devolve um array novo).

In [16]:
misto = np.array([1, 2.5, 3])
print(misto, misto.dtype)

inteiros = np.array([1, 2, 3])
print(inteiros.dtype)

como_float = inteiros.astype(float)
print(como_float, como_float.dtype)

texto = np.array([1, 'a', 3])
print(texto, texto.dtype)

[1.  2.5 3. ] float64
int64
[1. 2. 3.] float64
['1' 'a' '3'] <U21

## Posições de um array: contando a partir do zero
Cada valor tem um "endereço": a posição (índice).

|  | 1º | 2º | 3º | 4º | 5º |
|---|---|---|---|---|---|
| Posição | 0 | 1 | 2 | 3 | 4 |
| Posição negativa | -5 | -4 | -3 | -2 | -1 |
| Valor (preço) | 28.9 | 8.5 | 5.2 | 18.9 | 5.8 |

⚠️  A contagem começa em ZERO. O -1 é sempre o último elemento, sem precisar saber o tamanho.

## Indexação: pegando um elemento
Para pegar UM elemento, use colchetes com a posição. Também dá para trocar um valor:

💡  array[posição] pega um elemento · array[posição] = novo troca o valor · posição negativa conta do fim.

In [18]:
precos = np.array([28.9, 8.5, 5.2, 18.9, 5.8])

print(precos[0])
print(precos[2])
print(precos[-1])
print(precos[-2])

precos[1] = 9.0
print(precos)

28.9
5.2
5.8
18.9
[28.9  9.   5.2 18.9  5.8]

## Slicing: pegando uma fatia
Slicing pega vários elementos de uma vez, com [início:fim:passo]. O fim NÃO entra:

💡  [1:4] → posições 1, 2 e 3 · [:3] → do começo até a 2 · [2:] → da 2 até o fim · [::2] → de 2 em 2 · [::-1] → invertido

In [17]:
precos = np.array([28.9, 8.5, 5.2, 18.9, 5.8])

print(precos[1:4])
print(precos[:3])
print(precos[2:])
print(precos[::2])
print(precos[::-1])

[ 8.5  5.2 18.9]
[28.9  8.5  5.2]
[ 5.2 18.9  5.8]
[28.9  5.2  5.8]
[ 5.8 18.9  5.2  8.5 28.9]

## Indexação e slicing em 2D
Em arrays 2D usamos [linha, coluna]. O dois-pontos (:) significa "todos":

💡  Primeiro a LINHA, depois a COLUNA · mat[0, :] = toda a linha 0 · mat[:, 1] = toda a coluna 1

In [19]:
mat = np.array([[120, 150, 130, 160],
                [90, 110, 100, 130],
                [70, 80, 95, 85]])

print(mat[0, 0])
print(mat[1, 2])
print(mat[2, -1])
print(mat[0, :])
print(mat[:, 1])
print(mat[0:2, :])
print(mat[:, 0:2])

120
100
85
[120 150 130 160]
[150 110  80]
[[120 150 130 160]
 [ 90 110 100 130]]
[[120 150]
 [ 90 110]
 [ 70  80]]

## 🎯 Sua vez! — Desafio 1 · Criar e consultar arrays  (⏱ 7 min)

1. Crie preco_venda = [28.9, 8.5, 5.2, 18.9, 5.8] e custo = [20, 5, 3, 12, 3.5] como arrays. Mostre o shape e o dtype de cada um.
2. Mostre o primeiro preço, o último e os três primeiros (fatia).
3. Crie com arange os números de 1 a 12 e organize em uma matriz de 3 linhas e 4 colunas. Mostre a coluna 1 e a soma de cada linha.

💡 Dica: np.array([...]) · .shape / .dtype · preco[0], preco[-1], preco[:3] · np.arange(1, 13).reshape(3, 4) · m[:, 1] · m.sum(axis=1)

In [ ]:
# escreva sua solução aqui
preco_venda = np.array([28.9, 8.5, 5.2, 18.9, 5.8])
custo = np.array([20, 5, 3, 12, 3.5])

primeiro_preco = preco_venda[0]
ultimo_preco = preco_venda[-1]
tres_primeiros_precos = preco_venda[:3]
print(f"Shape Preço de Venda: {preco_venda.shape}")
print(f"Shape Custo: {custo.shape}")
print(f"Dtype Preço de Venda: {preco_venda.dtype}")
print(f"Dtype Custo: {custo.dtype}")
print(f"Primeiro preço: {primeiro_preco}")
print(f"Último preço: {ultimo_preco}")
print(f"Três primeiros preços: {tres_primeiros_precos}")

Shape Matriz 12: (2, 5)
Dtype Matriz 12: float64
Shape Preço de Venda: (5,)
Shape Custo: (5,)
Dtype Preço de Venda: float64
Dtype Custo: float64
Primeiro preço: 28.9
Último preço: 5.8
Três primeiros preços: [28.9  8.5  5.2]

## Filtrando com condições
A comparação gera Verdadeiro/Falso para cada elemento; colocada entre colchetes, mantém só os True:

💡  E = & · OU = | · NÃO = ~ · cada condição entre parênteses · é EXATAMENTE assim que o Pandas filtra linhas.

In [23]:
precos = np.array([28.9, 8.5, 5.2, 18.9, 5.8])
estoque = np.array([40, 120, 80, 35, 60])

print(precos > 10)
print(precos[precos > 10])
print(estoque[estoque < 50])

barato_e_cheio = (precos < 10) & (estoque > 70)
print(barato_e_cheio)
print(precos[barato_e_cheio])

[ True False False  True False]
[28.9 18.9]
[40 35]
[False  True  True False False]
[8.5 5.2]

## Cuidado: fatia é uma "janela", não uma cópia
Uma fatia (slice) mostra os MESMOS dados do array original. Mudar a fatia muda o original!

💡  Quer mexer sem afetar o original? Use .copy(). Sem .copy(), a fatia é só uma "janela" para o mesmo dado.

In [38]:
a = np.array([10, 20, 30, 40, 50])
fatia = a[1:4]
fatia[0] = 999
print(a)
print(fatia, end='\n\n')

b = np.array([10, 20, 30, 40, 50])
copia = b[1:4].copy()
copia[0] = 999
print(b)
print(copia)

[ 10 999  30  40  50]
[999  30  40]

[10 20 30 40 50]
[999  30  40]

## Contas elemento a elemento
As contas valem para TODOS os elementos, posição por posição. Nada de for:

💡  Os dois arrays precisam ter o mesmo tamanho (ou ser compatíveis, o broadcasting que vem logo adiante).

In [39]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 2, 3, 4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a * 1.10)

[ 3  6  9 12]
[1 2 3 4]
[ 2  8 18 32]
[2. 2. 2. 2.]
[ 4 16 36 64]
[2.2 4.4 6.6 8.8]

## Um caso do Mercadinho: faturamento
Preço × quantidade, item a item, e depois um resumo:

💡  argmax() devolve a POSIÇÃO do maior valor (e argmin() a do menor). Ligue a posição ao produto: 0 = Arroz.

In [40]:
precos = np.array([28.9, 8.5, 5.2, 18.9])
qtd = np.array([3, 10, 6, 2])

faturamento = np.round(precos * qtd, 2)
print(faturamento)
print('Total:', faturamento.sum())
print('Maior venda:', faturamento.max())
print('Posição da maior:', faturamento.argmax())

[86.7 85.  31.2 37.8]
Total: 240.7
Maior venda: 86.7
Posição da maior: 0

## Estatísticas rápidas
O array "se resume" em um número (ou em um número por linha/coluna):

💡  mean = média · median = mediana (valor do meio) · std = desvio padrão (o quanto os valores variam) · np.sqrt = raiz quadrada de cada um.

In [41]:
notas = np.array([7.0, 8.5, 6.0, 9.5, 5.5])

print(notas.sum())
print(notas.mean())
print(np.median(notas))
print(notas.max(), notas.min())
print(notas.std().round(2))
print(notas.argmax(), notas.argmin())
print(np.sqrt(notas).round(2))

36.5
7.3
7.0
9.5 5.5
1.5
3 4
[2.65 2.92 2.45 3.08 2.35]

## Tabela de números: matriz 2D

In [42]:
vendas_loja = np.array([[120, 150, 130, 160],
                        [ 90, 110, 100, 130],
                        [ 70,  80,  95,  85]])

print(vendas_loja.shape)
print(vendas_loja.sum(axis=1))  # total de cada LOJA
print(vendas_loja.sum(axis=0))  # total de cada SEMANA

(3, 4)
[560 430 330]
[280 340 325 375]

## Reshape: mudando a forma
reshape muda a FORMA do array sem mudar os dados. O total de elementos precisa ser o mesmo:

💡  O -1 significa "calcule você": reshape(4, -1) → 4 linhas e o Numpy descobre as colunas (3) · flatten() volta tudo para uma linha.

In [43]:
a = np.arange(1, 13)
print(a)

tabela = a.reshape(3, 4)
print(tabela)

print(a.reshape(4, -1).shape)
print(a.reshape(-1, 1).shape)
print(tabela.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(4, 3)
(12, 1)
[ 1  2  3  4  5  6  7  8  9 10 11 12]

## Broadcasting
O Numpy 'estica' o menor para caber no maior — sozinho.

## Broadcasting na prática
O Numpy "estica" o valor menor para caber no maior, sem você repetir nada:

💡  array + número aplica em todos · matriz + linha soma a linha em CADA linha da matriz.

In [44]:
precos = np.array([28.9, 8.5, 5.2, 18.9])
print(precos * 1.10)
print(precos + 2)

a = np.array([1, 2, 3])
print(a + 10)

mat = np.array([[1, 2, 3],
                [4, 5, 6]])
linha = np.array([10, 20, 30])
print(mat + linha)

[31.79  9.35  5.72 20.79]
[30.9 10.5  7.2 20.9]
[11 12 13]
[[11 22 33]
 [14 25 36]]

## Broadcasting em tabelas: metas por semana

In [23]:
meta_semana = np.array([100, 120, 110, 140])
print(vendas_loja - meta_semana)

[[ 20  30  20  20]
 [-10 -10 -10 -10]
 [-30 -40 -15 -55]]

## Quando o encaixe NÃO funciona
Se os tamanhos não combinam, o Numpy avisa com um erro — leia a mensagem, ela mostra os `shape`.

## Números aleatórios (random)
Gerar dados de teste e fazer simulações: um gerador com semente, para o resultado se repetir.

💡  seed fixa a "semente": com a mesma semente o resultado é sempre o mesmo · integers = inteiros · random = entre 0 e 1 · normal = distribuição normal · choice = sorteio.

In [53]:
rng = np.random.default_rng(seed=42)

print(rng.integers(1, 7, size=10))
print(rng.random(3).round(3))
print(rng.normal(50, 10, size=5).round(1))

vendas_sim = rng.integers(80, 200, size=(3, 4))
print(vendas_sim)
print(rng.choice(['Ana', 'Marcos', 'Rafael'], size=2, replace=False))

[1 5 4 3 3 6 1 5 2 1]
[0.976 0.761 0.786]
[49.8 41.5 58.8 57.8 50.7]
[[128 178 145 133]
 [134 107  91 146]
 [186  87 182 179]]
['Marcos' 'Ana']

## Numpy: resumo para consulta

| Para… | Use… |
|---|---|
| criar arrays | np.array([...]) · zeros · ones · arange · linspace |
| ver tamanho e tipo | .shape · .ndim · .size · .dtype |
| pegar um elemento | a[posição] · m[linha, coluna] |
| pegar uma fatia | a[início:fim:passo] · m[:, coluna] |
| filtrar | a[a > 10] · & (e) · \| (ou) · ~ (não) |
| fazer contas | + − * / ** (elemento a elemento) · broadcasting |
| resumir | .sum() · .mean() · .max() · .min() · .std() · axis= |
| mudar a forma | .reshape(linhas, colunas) · .flatten() |
| gerar dados | np.random.default_rng(seed) · integers · random |

✅  Se você dominou esta tabela, já sabe o suficiente de Numpy para entrar no Pandas.

### ❓ Quiz relâmpago ⚡

O que aparece ao rodar:  print(np.array([1, 2, 3]) * 2) ?

- **A)** [1, 2, 3, 1, 2, 3]
- **B)** [2 4 6]
- **C)** Dá erro
- **D)** 6

<details><summary>Ver resposta</summary>

**B)** Com Numpy, a multiplicação vale para cada elemento: [2 4 6]. (Se fosse lista Python comum, repetiria a lista: A.)

</details>

## 🎯 Sua vez! — Desafio 2 · Contas, filtros e broadcasting  (⏱ 8 min)

1. Calcule o lucro por unidade (preco_venda − custo) e o lucro total para as quantidades de qtd.
2. Mostre só os lucros maiores que R$ 5 e a POSIÇÃO do produto de maior lucro.
3. Aplique 15% de desconto em preco_venda (arredonde em 2 casas) e some R$ 1,00 de embalagem em todos.
4. Subtraia a meta semanal de vendas_loja e conte quantas células ficaram abaixo da meta.

💡 Dica: lucro * qtd com .sum() · lucro[lucro > 5] · .argmax() · np.round(preco * 0.85, 2) + 1 · (saldo < 0).sum()

In [54]:
preco_venda = np.array([28.9, 8.5, 5.2, 18.9, 5.8])
custo = np.array([20, 5, 3, 12, 3.5])
qtd = np.array([3, 10, 6, 2, 8])
vendas_loja = np.array([[120, 150, 130, 160],
                        [90, 110, 100, 130],
                        [70, 80, 95, 85]])
meta = np.array([100, 120, 110, 140])

In [26]:
# escreva sua solução aqui

# 🐼 Bloco 2 — Pandas: o básico

## O que é o Pandas?
Pandas é a biblioteca do Python para trabalhar com TABELAS: ler, limpar, filtrar, resumir e juntar dados.

- 📋 **Tabelas no Python**: Trabalha com dados em linhas e colunas, como uma planilha.
- 📂 **Lê de tudo**: CSV, Excel, JSON, SQL e dezenas de outros formatos.
- 🧰 **Faz o trabalho pesado**: Limpa, filtra, agrupa, junta e resume milhares de linhas em poucas linhas de código.

💡  O nome vem de "Panel Data" (dados em painel), termo da econometria. Foi criado por Wes McKinney em 2008 e usa o Numpy por baixo.

## Instalando e importando o Pandas
Mesma ideia do Numpy: instalar uma vez (no Colab já vem pronto) e importar com o apelido pd.

💡  openpyxl é a peça que o Pandas usa para ler arquivos Excel (.xlsx) · pd é o apelido universal.

In [55]:
# no terminal (só no seu computador):  pip install pandas openpyxl

print(pd.__version__)

3.0.6

## Excel × Pandas

## Dois personagens: Series e DataFrame
- **DataFrame** = a tabela inteira
- **Series** = uma coluna
- **index** = o rótulo (número) de cada linha

## Series: uma coluna com rótulos
Uma Series é UMA coluna: tem valores e tem rótulos (o índice). Como os preços de cada produto:

💡  Pense no índice como o nome de cada linha da planilha. Series aceita as mesmas contas do Numpy: precos * 1.10 reajusta todos.

In [60]:
precos = pd.Series([28.9, 8.5, 5.2, 18.9],
                   index=['Arroz', 'Feijão', 'Macarrão', 'Café'])

print(precos, end='\n\n')
print(f"Preço do Feijão: R${precos['Feijão']}", end='\n\n')
print(f"Valores: {precos.values}", end='\n\n')
print(f"Índices: {precos.index.tolist()}", end='\n\n')
print(f"Média: {precos.mean()}, Máximo: {precos.max()}", end='\n\n')
print(f"Preços com aumento de 10%:\n{precos * 1.10}", end='\n\n')

Arroz       28.9
Feijão       8.5
Macarrão     5.2
Café        18.9
dtype: float64

Preço do Feijão: R$8.5

Valores: [28.9  8.5  5.2 18.9]

Índices: ['Arroz', 'Feijão', 'Macarrão', 'Café']

Média: 15.375, Máximo: 28.9

Preços com aumento de 10%:
Arroz       31.79
Feijão       9.35
Macarrão     5.72
Café        20.79
dtype: float64

## DataFrame: uma tabela completa
Um DataFrame é uma tabela com linhas e colunas. Cada coluna é uma Series e pode ter um tipo diferente:

💡  Chave do dicionário = nome da coluna · lista = valores · uma coluna nova nasce de uma conta com colunas existentes.

In [61]:
mini = pd.DataFrame({
    'produto': ['Arroz', 'Feijão', 'Macarrão', 'Café'],
    'preco': [28.9, 8.5, 5.2, 18.9],
    'estoque': [40, 120, 80, 35]})
print(mini)

print(type(mini['preco']))

mini['valor_estoque'] = mini['preco'] * mini['estoque']
print(mini)
print(mini.shape)

    produto  preco  estoque
0     Arroz   28.9       40
1    Feijão    8.5      120
2  Macarrão    5.2       80
3      Café   18.9       35
<class 'pandas.Series'>
    produto  preco  estoque  valor_estoque
0     Arroz   28.9       40         1156.0
1    Feijão    8.5      120         1020.0
2  Macarrão    5.2       80          416.0
3      Café   18.9       35          661.5
(4, 4)

## Index: o endereço de cada linha
Por padrão o índice é 0, 1, 2…; com set_index você troca pelo nome do produto e localiza linhas pelo nome:

💡  loc → pelo RÓTULO (nome) · iloc → pela POSIÇÃO (número) · reset_index() devolve o índice numérico.

In [63]:
tabela = mini.set_index('produto')
print(tabela, end='\n\n')

print(tabela.loc['Café'], end='\n\n')
print(tabela.iloc[0], end='\n\n')
print(tabela.index.tolist(), end='\n\n')
print(tabela.reset_index().columns.tolist(), end='\n\n')

          preco  estoque  valor_estoque
produto
Arroz      28.9       40         1156.0
Feijão      8.5      120         1020.0
Macarrão    5.2       80          416.0
Café       18.9       35          661.5

preco             18.9
estoque           35.0
valor_estoque    661.5
Name: Café, dtype: float64

preco              28.9
estoque            40.0
valor_estoque    1156.0
Name: Arroz, dtype: float64

['Arroz', 'Feijão', 'Macarrão', 'Café']

['produto', 'preco', 'estoque', 'valor_estoque']

## Tipos de dados (dtype)
Cada coluna do DataFrame tem um tipo, e o tipo define o que dá para fazer com ela:

| dtype | O que guarda | Exemplo | Serve para |
|---|---|---|---|
| int64 | números inteiros | 40, 120 | contar, somar |
| float64 | números decimais | 28.9, 8.5 | preços, médias |
| object | texto | Arroz, Feijão | nomes, categorias |
| bool | verdadeiro / falso | True, False | filtros |
| datetime64 | datas e horas | 2026-08-01 | diferenças, meses |

⚠️  Tipo errado = cálculo errado. Um número guardado como texto (object) não soma. Confira com df.dtypes ou df.info().

## De onde vêm os dados?
`read_csv`, `read_excel`, `read_json`, `read_sql` → todos devolvem um **DataFrame**.

## Mesmo dado, 3 formatos

In [31]:
df_csv   = pd.read_csv('dados/produtos.csv')
df_excel = pd.read_excel('dados/produtos.xlsx')
df_json  = pd.read_json('dados/produtos.json')

print(df_csv.shape, df_excel.shape, df_json.shape)

(12, 5) (12, 5) (12, 5)

## A nossa tabela de produtos

In [32]:
produtos = pd.read_csv('dados/produtos.csv')
produtos

    id_produto           produto   categoria  preco  estoque
0            1         Arroz 5kg   Mercearia   28.9       40
1            2        Feijão 1kg   Mercearia    8.5      120
2            3     Macarrão 500g   Mercearia    5.2       80
3            4         Café 500g   Mercearia   18.9       35
4            5          Leite 1L  Laticínios    5.8       60
5            6       Queijo 500g  Laticínios   24.9       18
6            7      Iogurte 170g  Laticínios    3.5       90
7            8   Refrigerante 2L     Bebidas    9.9       70
8            9           Suco 1L     Bebidas    7.4       45
9           10   Sabão em pó 1kg     Limpeza   14.9       30
10          11  Detergente 500ml     Limpeza    2.8      150
11          12     Shampoo 350ml     Higiene   12.5       25

## Primeiro olhar: shape e dtypes

In [33]:
print(produtos.shape)   # (linhas, colunas)
produtos.dtypes

(12, 5)

id_produto      int64
produto        object
categoria      object
preco         float64
estoque         int64
dtype: object

## O raio-X: info()

In [34]:
produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_produto  12 non-null     int64
 1   produto     12 non-null     object
 2   categoria   12 non-null     object
 3   preco       12 non-null     float64
 4   estoque     12 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 612.0+ bytes

## Resumo estatístico: describe()

In [35]:
produtos[['preco', 'estoque']].describe().round(2)

       preco  estoque
count  12.00    12.00
mean   11.93    63.58
std     8.46    40.55
min     2.80    18.00
25%     5.65    33.75
50%     9.20    52.50
75%    15.90    82.50
max    28.90   150.00

## Escolhendo colunas

In [36]:
nomes = produtos['produto']
print(type(nomes))

produtos[['produto', 'preco']].head(3)

<class 'pandas.core.series.Series'>

         produto  preco
0      Arroz 5kg   28.9
1     Feijão 1kg    8.5
2  Macarrão 500g    5.2

## Criando colunas novas

In [37]:
produtos['preco_novo'] = (produtos['preco'] * 1.10).round(2)
produtos['valor_estoque'] = produtos['preco'] * produtos['estoque']

produtos[['produto', 'preco', 'preco_novo', 'valor_estoque']].head(4)

         produto  preco  preco_novo  valor_estoque
0      Arroz 5kg   28.9       31.79         1156.0
1     Feijão 1kg    8.5        9.35         1020.0
2  Macarrão 500g    5.2        5.72          416.0
3      Café 500g   18.9       20.79          661.5

## Ordenando: os mais caros

In [38]:
caros = produtos.sort_values('preco', ascending=False)
caros[['produto', 'preco']].head(3)

       produto  preco
0    Arroz 5kg   28.9
5  Queijo 500g   24.9
3    Café 500g   18.9

## Contando: value_counts()

In [39]:
produtos['categoria'].value_counts()

categoria
Mercearia     4
Laticínios    3
Bebidas       2
Limpeza       2
Higiene       1
Name: count, dtype: int64

## 🎯 Sua vez! — Desafio 3  (⏱ 7 min)

1. Crie a coluna `preco_promo` com 15% de desconto (arredonde em 2 casas).
2. Calcule o valor total em estoque (some a coluna `valor_estoque`).
3. Mostre os 3 produtos mais baratos (nome e preço).

💡 *Dica: desconto de 15% = multiplicar por 0.85. Soma de uma coluna: produtos['coluna'].sum().*

In [40]:
# escreva sua solução aqui

# 🔎 Bloco 3 — Filtrar e selecionar

## Nova tabela: as vendas

In [41]:
vendas = pd.read_csv('dados/vendas.csv')
vendas['valor_total'] = (vendas['quantidade'] * vendas['preco_unit']).round(2)
vendas[['data', 'produto', 'quantidade', 'preco_unit', 'vendedor', 'valor_total']].head(6)

         data          produto  quantidade  preco_unit  vendedor  valor_total
0  2026-08-01          Suco 1L           4         7.4    Rafael         29.6
1  2026-08-02         Leite 1L           5         5.8    Marcos         29.0
2  2026-08-03  Sabão em pó 1kg           5        14.9    Marcos         74.5
3  2026-08-04  Refrigerante 2L           1         9.9    Marcos          9.9
4  2026-08-04        Arroz 5kg           5        28.9  Patrícia        144.5
5  2026-08-04    Shampoo 350ml           4        12.5  Patrícia         50.0

## loc × iloc
- `loc` → pelo **nome** (rótulo)
- `iloc` → pela **posição** (número, começa em 0)

## loc: pelo nome

In [42]:
p = produtos.set_index('produto')[['categoria', 'preco', 'estoque']]

print(p.loc['Café 500g'])           # a linha inteira
print(p.loc['Café 500g', 'preco'])  # uma célula

categoria    Mercearia
preco             18.9
estoque             35
Name: Café 500g, dtype: object
18.9

## iloc: pela posição

In [43]:
print(p.iloc[3])        # 4ª linha (começa em 0!)
print(p.iloc[3, 1])     # linha 3, coluna 1

p.iloc[0:3]             # linhas 0, 1 e 2

categoria    Mercearia
preco             18.9
estoque             35
Name: Café 500g, dtype: object
18.9

               categoria  preco  estoque
produto
Arroz 5kg      Mercearia   28.9       40
Feijão 1kg     Mercearia    8.5      120
Macarrão 500g  Mercearia    5.2       80

## Filtrando: pergunta que vira Verdadeiro/Falso
Passo 1: `produtos['preco'] > 10` → True/False por linha.
Passo 2: `produtos[...]` mantém só as linhas True.

## Filtro simples

In [44]:
produtos[produtos['preco'] > 10][['produto', 'categoria', 'preco']]

            produto   categoria  preco
0         Arroz 5kg   Mercearia   28.9
3         Café 500g   Mercearia   18.9
5       Queijo 500g  Laticínios   24.9
9   Sabão em pó 1kg     Limpeza   14.9
11    Shampoo 350ml     Higiene   12.5

## Combinando condições
| Símbolo | Significa | Exemplo |
|---|---|---|
| `&` | E (as duas) | barato **E** mercearia |
| `\|` | OU (uma delas) | bebidas **OU** limpeza |
| `~` | NÃO | **não** é mercearia |

## Filtro com E (&)

In [45]:
mercearia = produtos['categoria'] == 'Mercearia'
barato = produtos['preco'] < 10

produtos[mercearia & barato][['produto', 'preco']]

         produto  preco
1     Feijão 1kg    8.5
2  Macarrão 500g    5.2

## Filtros com OU (|) e NÃO (~)

In [46]:
bebida = produtos['categoria'] == 'Bebidas'
limpeza = produtos['categoria'] == 'Limpeza'

print(produtos[bebida | limpeza]['produto'].tolist())
print(produtos[~mercearia].shape[0], 'produtos não são de mercearia')

['Refrigerante 2L', 'Suco 1L', 'Sabão em pó 1kg', 'Detergente 500ml']
8 produtos não são de mercearia

## Erros comuns nos filtros
1. Usar `and` no lugar de `&` → *ValueError: truth value of a Series is ambiguous*
2. Esquecer os parênteses: `df['a'] > 1 & df['b'] < 5`
3. Usar `=` no lugar de `==` → *SyntaxError*

## Atalhos de filtro: isin, between, contains

In [47]:
print(produtos[produtos['categoria'].isin(['Bebidas', 'Limpeza'])]['produto'].tolist())
print(produtos[produtos['preco'].between(5, 10)]['produto'].tolist())
print(produtos[produtos['produto'].str.contains('kg')]['produto'].tolist())

['Refrigerante 2L', 'Suco 1L', 'Sabão em pó 1kg', 'Detergente 500ml']
['Feijão 1kg', 'Macarrão 500g', 'Leite 1L', 'Refrigerante 2L', 'Suco 1L']
['Arroz 5kg', 'Feijão 1kg', 'Sabão em pó 1kg']

### ❓ Quiz relâmpago ⚡

Qual código traz as vendas do vendedor 'Marcos' pagas em 'Pix'?

- **A)** vendas[vendas['vendedor'] == 'Marcos' and vendas['pagamento'] == 'Pix']
- **B)** vendas[(vendas['vendedor'] == 'Marcos') & (vendas['pagamento'] == 'Pix')]
- **C)** vendas[vendas['vendedor'] = 'Marcos' & vendas['pagamento'] = 'Pix']
- **D)** vendas['vendedor' == 'Marcos', 'pagamento' == 'Pix']

<details><summary>Ver resposta</summary>

**B)** Duas condições com == , cada uma entre parênteses, ligadas por &.

</details>

## 🎯 Sua vez! — Desafio 4  (⏱ 8 min)

1. Quantas vendas o vendedor Marcos fez pagas no Pix? (use `.shape[0]` ou `len`)
2. Mostre as vendas de Bebidas ou Limpeza com `valor_total` maior que 30.
3. Mostre as 5 maiores vendas (colunas: data, produto, valor_total).

💡 *Dica: guarde cada condição numa variável; para o item 3, sort_values('valor_total', ascending=False).*

In [48]:
# escreva sua solução aqui

# 📊 Bloco 4 — Agrupar e resumir

## Groupby: dividir, calcular e juntar
1. **Dividir** as linhas por grupo (vendedor)
2. **Calcular** (somar, contar, tirar média…)
3. **Juntar** o resultado

## groupby: faturamento por vendedor

In [49]:
vendas.groupby('vendedor')['valor_total'].sum().round(2)

vendedor
Marcos      1968.1
Patrícia    1674.8
Rafael      1558.7
Name: valor_total, dtype: float64

## Ranking de categorias

In [50]:
ranking = vendas.groupby('categoria')['valor_total'].sum()
ranking.sort_values(ascending=False).round(2)

categoria
Mercearia     2558.2
Laticínios    1038.1
Bebidas        922.4
Limpeza        557.9
Higiene        125.0
Name: valor_total, dtype: float64

## Contar e tirar média

In [51]:
print(vendas.groupby('vendedor')['id_venda'].count())
print()
print(vendas.groupby('pagamento')['valor_total'].mean().round(2))

vendedor
Marcos      47
Patrícia    40
Rafael      33
Name: id_venda, dtype: int64

pagamento
Cartão      48.93
Dinheiro    28.24
Pix         41.88
Name: valor_total, dtype: float64

## agg: várias contas de uma vez

In [52]:
resumo = vendas.groupby('categoria').agg(
    faturamento=('valor_total', 'sum'),
    ticket_medio=('valor_total', 'mean'),
    n_vendas=('id_venda', 'count')
).round(2)
resumo

            faturamento  ticket_medio  n_vendas
categoria
Bebidas           922.4         32.94        28
Higiene           125.0         25.00         5
Laticínios       1038.1         37.07        28
Limpeza           557.9         46.49        12
Mercearia        2558.2         54.43        47

## pivot_table = Tabela Dinâmica
`index` → linhas · `columns` → colunas · `values` → o que calcular · `aggfunc` → como calcular

## pivot_table na prática

In [53]:
vendas.pivot_table(index='vendedor', columns='pagamento',
                   values='valor_total', aggfunc='sum',
                   fill_value=0).round(0)

pagamento  Cartão  Dinheiro    Pix
vendedor
Marcos     1039.0     106.0  823.0
Patrícia   1001.0      68.0  606.0
Rafael      504.0     222.0  833.0

## 🎯 Sua vez! — Desafio 5  (⏱ 8 min)

1. Faturamento (soma de `valor_total`) por categoria, do maior para o menor.
2. Ticket médio (média de `valor_total`) por forma de pagamento.
3. Tabela dinâmica: categoria nas linhas × vendedor nas colunas, somando `quantidade`.

💡 *Dica: é só trocar as colunas do groupby/pivot_table que acabamos de ver.*

In [54]:
# escreva sua solução aqui

# 🔗 Bloco 5 — Juntar tabelas

## Merge: o PROCV do Python
A tabela **vendas** só tem o `id_cliente`. Nome e cidade estão na tabela **clientes**. O `merge` cola as duas usando a **chave** em comum.

## merge na prática

In [55]:
clientes = pd.read_csv('dados/clientes.csv')
completo = vendas.merge(clientes, on='id_cliente', how='left')
completo[['id_venda', 'id_cliente', 'nome', 'cidade', 'valor_total']].head(5)

   id_venda  id_cliente            nome         cidade  valor_total
0      1001           6     Fábio Costa      Joinville         29.6
1      1002           7  Gabriela Nunes  Florianópolis         29.0
2      1003           1       Ana Souza  Florianópolis         74.5
3      1004           4     Diego Alves       Blumenau          9.9
4      1005           1       Ana Souza  Florianópolis        144.5

## E o cliente que não está no cadastro?

In [56]:
completo[completo['id_cliente'] == 99][['id_venda', 'id_cliente', 'nome', 'cidade', 'valor_total']].head(4)

    id_venda  id_cliente nome cidade  valor_total
11      1012          99  NaN    NaN          8.4
16      1017          99  NaN    NaN         49.8
22      1023          99  NaN    NaN         12.5
49      1050          99  NaN    NaN         51.0

## how=: quais linhas ficam?
- `inner` → só quem existe nas duas tabelas
- `left` → todas da esquerda ⭐
- `right` → todas da direita
- `outer` → tudo

## Contando as linhas de cada how

In [57]:
for how in ['inner', 'left', 'right', 'outer']:
    n = vendas.merge(clientes, on='id_cliente', how=how).shape[0]
    print(how, '->', n, 'linhas')

inner -> 107 linhas
left -> 120 linhas
right -> 109 linhas
outer -> 122 linhas

## Respondendo ao dono: vendas por cidade

In [58]:
completo['cidade'] = completo['cidade'].fillna('Sem cadastro')
completo.groupby('cidade')['valor_total'].sum().sort_values(ascending=False).round(2)

cidade
Joinville        1613.5
Florianópolis    1459.7
Chapecó           624.9
Blumenau          583.5
Sem cadastro      511.2
Criciúma          408.8
Name: valor_total, dtype: float64

## concat: empilhando tabelas
`pd.concat([ago, setembro])` junta tabelas com as **mesmas colunas**, uma embaixo da outra.

## concat na prática

In [59]:
agosto = pd.read_csv('dados/vendas_agosto.csv')
setembro = pd.read_csv('dados/vendas_setembro.csv')

todas = pd.concat([agosto, setembro], ignore_index=True)
print(agosto.shape, setembro.shape, todas.shape)

(59, 9)

 (61, 9) (120, 9)

## 3 cuidados ao juntar tabelas
1. Conferir o `shape` antes e depois
2. Chave com mesmo tipo e mesmo sentido nas duas tabelas
3. Chaves repetidas multiplicam linhas

# 🏆 Case final

## 🎯 Sua vez! — Desafio 6  (⏱ 15 min)

1. Quais os 3 produtos mais vendidos em quantidade? (groupby em `vendas`)
2. Clientes fidelidade 'Sim' gastam mais (em média) que os 'Não'? (use `completo`)
3. Qual cidade tem o maior ticket médio?
4. Quem é o melhor vendedor em Joinville (maior faturamento)?

💡 *Dica: itens 2, 3 e 4 usam o `completo` (vendas + clientes). O item 4 combina filtro + groupby.*

In [60]:
# escreva sua solução aqui